[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm install", "npm --prefix server install"]

[phases.build]
cmds = ["npm run build", "npm --prefix server run build"]

[start]
cmd = "npm --prefix server run db:migrate && npm --prefix server run start"
